export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_MESSAGE_PAGE = 'ADD_MESSAGE_PAGE';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
export const UPDATE_TOTAL_PAGES = 'UPDATE_TOTAL_PAGES';

